---
- name: Deployment in tomcat
  hosts: 127.0.0.1
  tasks: 
  - name: install apache
    yum:
      name: httpd
      state: present

  - name: start apache
    service:
      name: httpd
      state: started
      enabled: true

  - name: copy index.html file
    copy: 
      src: /tmp/index.html
      dest: /var/www/html
