---
#- name: Run playbook to create Loadbalancer  ##  Run this playbook with old inventory 
#  import_playbook: create-loadbalancer.yaml  ##  ansible-playbook -i ../../../k8s-cluster/ansible/inventory/hosts create-loadbalancer.yaml 
#
- name: Run playbook to create kubernetes cluster
  import_playbook: create-kubernetes-cluster.yaml

- name: Run playbook to join other master nodes to kubernetes cluster
  import_playbook: clusterjoin.yaml

- name: Run playbook to join other master nodes to kubernetes cluster
  import_playbook: workernode.yaml
