---
- name: Join remaining master nodes to the cluster
  hosts: master-23
  tasks: 
  - name: copy token to master and worker nodes
    copy:
      src: join_token
      dest: join_token
  
  - name: Attach master to the kubernetes cluster
    shell: |
             kubeadm reset -f
             tail -12 join_token > cluster-script
             cat cluster-script | head -3 > k8s-master.sh
             /bin/sh k8s-master.sh
