---
- name: create Loadbalancer
  hosts: loadbalancer
  become: true
  tasks:
  - name: copy haproxy content to loadbalancer 1
    copy: 
      src: haproxy-loadbalancer-master.conf
      dest: /etc/haproxy/haproxy.cfg
    delegate_to: "{{ groups['loadbalancer'][0] }}"
  - name: copy haproxy content to loadbalancer 2
    copy: 
      src: haproxy-loadbalancer-backup.conf
      dest: /etc/haproxy/haproxy.cfg
    delegate_to: "{{ groups['loadbalancer'][1] }}"
  - name: Start haproxy service
    service:
      name: haproxy
      state: started
      enabled: true
